const { _electron: electron } = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const output = path.resolve('test-results'); await fs.mkdir(output,{recursive:true});
  const profile = await fs.mkdtemp(path.join(output,'profiles-ui-'));
  const env = {...process.env,CAESER_TEST_DATA:profile}; delete env.ELECTRON_RUN_AS_NODE;
  const options = {args:process.env.CAESER_TEST_EXE ? [] : ['.'],...(process.env.CAESER_TEST_EXE ? {executablePath:process.env.CAESER_TEST_EXE} : {}),env};
  let app; const errors=[]; let savedId;
  const boot = async () => {
    app = await electron.launch(options); const page = await app.firstWindow();
    page.on('pageerror',e=>errors.push(e.message));
    await page.waitForFunction(()=>document.getElementById('connection-label').textContent !== 'Versionen laden …',null,{timeout:60000});
    return page;
  };
  try {
    let page = await boot();
    assert.equal(await page.locator('nav [data-page]').count(),4);
    await page.locator('[data-page="profiles"]').click(); await page.locator('#new-profile').click();
    await page.locator('#profile-name').fill('Survival mit Freunden');
    await page.locator('#profile-version').selectOption('1.21.11'); await page.locator('[data-loader="fabric"]').click();
    await page.locator('#profile-memory').fill('3072');
    assert.match(await page.locator('#profile-memory-value').textContent(),/3072 MB/);
    await page.screenshot({path:path.join(output,'profile-editor.png')});
    await page.locator('#save-profile').click(); await page.waitForFunction(()=>!document.getElementById('profile-dialog').open,null,{timeout:60000});
    let state = await page.evaluate(()=>window.caeser.state());
    const created=state.profiles.find(p=>p.name==='Survival mit Freunden'); assert.ok(created); savedId=created.id;
    assert.equal(created.mode,'fabric'); assert.equal(created.memoryMb,3072); assert.equal(state.activeProfileId,savedId);
    const card=page.locator('.profile-card').filter({hasText:'Survival mit Freunden'});
    await card.locator('.edit-profile').click(); assert.equal(await page.locator('#profile-version').isDisabled(),true);
    await page.locator('#profile-name').fill('Meine Survival-Welt'); await page.locator('#profile-memory').fill('5120');
    await page.locator('#save-profile').click(); await page.waitForFunction(()=>!document.getElementById('profile-dialog').open);
    await page.locator('[data-page="play"]').click(); assert.equal(await page.locator('#selected-name').textContent(),'Meine Survival-Welt');
    assert.match(await page.locator('#selected-meta').textContent(),/5120 MB/);
    await page.locator('#play-button').click(); assert.ok(await page.locator('#accounts-dialog').evaluate(el=>el.open));
    assert.equal(await page.locator('#client-id').count(),0);
    await page.locator('[data-close="accounts-dialog"]').click();
    await page.locator('[data-page="settings"]').click();
    await page.locator('[data-settings-category="themes"]').click();
    await page.locator('[data-theme="Aurora"]').click(); await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--accent')==='#00e8b8');
    await page.locator('[data-theme="Ultraviolet"]').click();
    await page.locator('[data-page="play"]').click(); await page.evaluate(()=>{document.getElementById('toast').hidden=true;document.body.classList.add('no-animation');});
    await page.screenshot({path:path.join(output,'caeser-client-v2.png')});
    const layout=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,content:document.querySelector('.content').clientWidth,contentScroll:document.querySelector('.content').scrollWidth}));
    assert.equal(layout.width,layout.scroll);assert.equal(layout.content,layout.contentScroll);
    // Exercise Windows safeStorage on a synthetic session without logging into Microsoft.
    const testAccount = {id:'synthetic-test-account',name:'Speicher-Test',refreshToken:'synthetic-refresh-token',accessToken:'synthetic-access-token',expiresAt:0,clientId:'test'};
    const secondAccount = {...testAccount,id:'synthetic-second-account',name:'Zweites-Konto'};
    const encrypted = await app.evaluate(({ safeStorage }, accounts) => Array.from(safeStorage.encryptString(JSON.stringify(accounts))), [testAccount,secondAccount]);
    await fs.writeFile(path.join(profile,'accounts.bin'),Buffer.from(encrypted));
    const settingsFile=path.join(profile,'settings.json'), savedSettings=JSON.parse(await fs.readFile(settingsFile,'utf8'));
    savedSettings.activeAccount=testAccount.id; await fs.writeFile(settingsFile,JSON.stringify(savedSettings));
    assert.equal((await fs.readFile(path.join(profile,'accounts.bin'))).includes(Buffer.from('synthetic-refresh-token')),false);
    await app.close(); app=null;
    page=await boot(); state=await page.evaluate(()=>window.caeser.state());
    assert.equal(state.activeProfileId,savedId); assert.equal(state.profiles.find(p=>p.id===savedId).memoryMb,5120);
    assert.equal(state.accounts[0].name,'Speicher-Test'); assert.ok(!JSON.stringify(state).includes('synthetic-refresh-token'));
    await page.locator('#account-chip').click();
    assert.equal(await page.locator('.account-option').count(),2);
    assert.equal(await page.locator('.account-option .skin-head img').count(),2);
    await page.locator('.choose-account').filter({hasText:'Zweites-Konto'}).click();
    await page.waitForFunction(()=>document.getElementById('account-name').textContent==='Zweites-Konto');
    assert.equal((await page.evaluate(()=>window.caeser.state())).settings.activeAccount,'synthetic-second-account');
    await page.locator('#account-chip').click();
    await page.locator('.account-option').filter({hasText:'Zweites-Konto'}).locator('.remove-menu-account').click();
    await page.waitForFunction(()=>document.getElementById('account-name').textContent==='Speicher-Test');
    await page.keyboard.press('Escape');
    await page.evaluate(()=>window.caeser.removeAccount('synthetic-test-account'));
    assert.equal(await page.locator('#selected-name').textContent(),'Meine Survival-Welt');
    await page.locator('[data-page="profiles"]').click();
    await page.screenshot({path:path.join(output,'profiles-v2.png')});
    await page.locator('.profile-card').filter({hasText:'Meine Survival-Welt'}).locator('.delete-profile').click();
    await page.locator('#confirm-delete').click(); await page.waitForFunction(()=>!document.getElementById('delete-dialog').open);
    assert.equal((await page.evaluate(()=>window.caeser.state())).profiles.some(p=>p.id===savedId),false);
    assert.deepEqual(errors,[]);
    console.log('UI passed: profile create/edit/delete, isolated settings, MB slider, real catalogue, mode selection, restart persistence, account gate, client-ID validation, theme changes, layout.');
  } finally { if(app) await app.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
